'use client';
import React, { useState, useContext, useEffect } from "react";

import type { Metadata } from 'next'
import './globals.css'
import {SwapTokenContextProvider} from '../Context/SwapContext';

export const metadata: Metadata = {
  title: 'Uniswap Clone',
  description: 'Generated by Iftikhar uddin',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <SwapTokenContextProvider>
      {children}
      </SwapTokenContextProvider>
      </body>
    </html>
  )
}
